### ISSUE TITLE
ICE Deprecated

### ISSUE THREAD

**Issue by krsyoung** [Osthanes/utilities#112]
Hey, the ice command has been deprecated as of Jan 2016.  Are there plans to update this repo to make use of the `cf ic` command?

https://console.ng.bluemix.net/docs/containers/container_cli_ice_ov.html

**Comment by jgarcows** [comment]
This is actively being developed in the bahram-cfic branch.

**Comment by krsyoung** [comment]
Ah cool, thanks @jgarcows!  Any chance you know of an ETA on it being integrated with the DevOps build pipeline  (seems like that piece is out of our control and based on cloning from the `master` branch).

**Comment by nfritze** [comment]
Completed.  (sorry for the delay on updating the issue - this actually went live end of march)
