### ISSUE TITLE
Update Docker Version

### ISSUE THREAD

**Issue by leifg** [Osthanes/utilities#129]
I noticed that in my builds Version 1.6 of Docker is used. Is there any way to ship a newer (the current) version?

**Comment by jgarcows** [comment]
We have a branch in testing to use a newer version of Docker.  If you want to try it out before it is released in prod, you can set OVERRIDE_UTILITIES_BRANCH=newDocker in your stage environment variables.

**Comment by leifg** [comment]
Oh didn't see, that's great.

**Comment by jgarcows** [comment]
Docker is now at version 1.13 by default in the pipeline, you no longer need to use OVERRIDE_UTILITIES_BRANCH
